/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Configuration options for the logger
 * @param {string} [level] - Log level (trace, debug, info, warn, error). Defaults to "info"
 * @param {boolean} [json] - Whether to output logs in JSON format. Defaults to false
 */
export interface LoggerOptions {
  level?: string
  json?: boolean
}
export declare class Logger {
  /**
   * Creates a new logger instance
   * @param {string} name - The name of the service that will be displayed in logs
   * @param {LoggerOptions} [options] - Configuration options for the logger
   * @returns {Logger} A new Logger instance
   */
  constructor(name: string, options?: LoggerOptions | undefined | null)
  /**
   * Logs a debug message
   * @param {string} message - The message to log at debug level
   */
  debug(message: string): void
  /**
   * Logs an info message
   * @param {string} message - The message to log at info level
   */
  info(message: string): void
  /**
   * Logs a warning message
   * @param {string} message - The message to log at warn level
   */
  warn(message: string): void
  /**
   * Logs an error message
   * @param {string} message - The message to log at error level
   */
  error(message: string): void
}
